use floreria_app;
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('01', 'Aguascalientes', 'Ags.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('02', 'Baja California', 'BC', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('03', 'Baja California Sur', 'BCS', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('04', 'Campeche', 'Camp.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('05', 'Coahuila de Zaragoza', 'Coah.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('06', 'Colima', 'Col.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('07', 'Chiapas', 'Chis.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('08', 'Chihuahua', 'Chih.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('09', 'Ciudad de México', 'CDMX', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('10', 'Durango', 'Dgo.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('11', 'Guanajuato', 'Gto.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('12', 'Guerrero', 'Gro.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('13', 'Hidalgo', 'Hgo.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('14', 'Jalisco', 'Jal.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('15', 'México', 'Mex.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('16', 'Michoacán de Ocampo', 'Mich.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('17', 'Morelos', 'Mor.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('18', 'Nayarit', 'Nay.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('19', 'Nuevo León', 'NL', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('20', 'Oaxaca', 'Oax.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('21', 'Puebla', 'Pue.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('22', 'Querétaro', 'Qro.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('23', 'Quintana Roo', 'Q. Roo', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('24', 'San Luis Potosí', 'SLP', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('25', 'Sinaloa', 'Sin.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('26', 'Sonora', 'Son.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('27', 'Tabasco', 'Tab.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('28', 'Tamaulipas', 'Tamps.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('29', 'Tlaxcala', 'Tlax.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('30', 'Veracruz de Ignacio de la Llave', 'Ver.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('31', 'Yucatán', 'Yuc.', 1);
INSERT INTO entidad(ent_id, ent_nom, ent_abr, pai_id) VALUES ('32', 'Zacatecas', 'Zac.', 1);